### ISSUE TITLE
RuntimeError: Failed to acquire interface: omni::isaac::motion_planning::MotionPlanning (pluginName: nullptr)

### ISSUE THREAD

**Issue by newuhe** [erasromani/isaac-sim-python#1]
hi @ssilwal , I followed the instructions and ran the sample`python simulate_grasp.py -P Isaac/Props/Flip_Stack/large_corner_bracket_physics.usd Isaac/Props/Flip_Stack/screw_95_physics.usd Isaac/Props/Flip_Stack/t_connector_physics.usd -l nucleus_server -p 40 0 5 -a 45 -n 5 -v sim.mp4
`

then I encountered the following problem:
```
[Warning] [omni.kit.app.plugin] --carb/app/extensions/folders2/0="/home/flexivsu/isaac-sim/_build/target-deps/kit_sdk_release/_build/linux-x86_64/release/exts": prefix '--carb/' is deprecated. Override should be --/app/extensions/folders2/0="/home/flexivsu/isaac-sim/_build/target-deps/kit_sdk_release/_build/linux-x86_64/release/exts"
[Warning] [omni.kit.app.plugin] --carb/app/extensions/folders2/1="/home/flexivsu/isaac-sim/_build/target-deps/kit_sdk_release/_build/linux-x86_64/release/extsPhysics": prefix '--carb/' is deprecated. Override should be --/app/extensions/folders2/1="/home/flexivsu/isaac-sim/_build/target-deps/kit_sdk_release/_build/linux-x86_64/release/extsPhysics"
[Warning] [omni.kit.app.plugin] --carb/app/extensions/folders2/2="/home/flexivsu/isaac-sim/_build/linux-x86_64/release/exts": prefix '--carb/' is deprecated. Override should be --/app/extensions/folders2/2="/home/flexivsu/isaac-sim/_build/linux-x86_64/release/exts"
[Info] [carb] Logging to file: /home/flexivsu/isaac-sim/_build/target-deps/kit_sdk_release/_build/linux-x86_64/release/data/Kit/isaac-sim-python/2020.2.28460/omniverse-kit.log
2021-05-12 07:53:53 [3ms] [Warning] [omni.kit.app.plugin] [Graphics API] Vulkan

[0.042s] [ext: omni.timeline-0.1.0] startup
[0.056s] [ext: omni.kit.async_engine-0.1.0] startup
[0.057s] [ext: omni.assets-0.1.0] startup
[0.058s] [ext: omni.kit.test-0.1.0] startup
[0.061s] [ext: omni.usd-0.1.0] startup
[0.098s] [ext: omni.client-0.1.0] startup
2021-05-12 07:53:53 [87ms] [Warning] [carb] Acquiring non optional plugin interface which is not listed as dependency: [carb::tokens::ITokens v0.1] (plugin: (null)), by client: omni.client.plugin. Add it to CARB_PLUGIN_IMPL_DEPS() macro of a client.
[0.112s] [ext: omni.kit.registry.nucleus-0.1] startup
[0.116s] [ext: omni.kit.pipapi-0.1.0] startup
[0.338s] [ext: omni.stats-0.1.0] startup
[0.342s] [ext: omni.kit.pip_archive-0.1] startup
2021-05-12 07:53:54 [331ms] [Warning] [carb.python] There is already a module 'toml' in '/home/flexivsu/.local/lib/python3.6/site-packages/toml/__init__.py'. Can't import another module with the same name in public space from '/home/flexivsu/isaac-sim/_build/target-deps/kit_sdk_release/_build/linux-x86_64/release/exts/omni.kit.pip_archive-0.1/pip_prebundle'.
[0.356s] [ext: omni.appwindow-0.1.0] startup
[0.363s] [ext: omni.kit.commands-0.1] startup
[0.385s] [ext: omni.ansel-0.1.0] startup
[0.387s] [ext: omni.ui-1.0.0] startup
[0.397s] [ext: omni.renderer-0.1.0-rtx] startup
[0.398s] [ext: omni.kit.editor-0.1.0-full] startup

|---------------------------------------------------------------------------------------|
| Driver Version: 450.119
|=======================================================================================|
| GPU | Name                             | Active | GPU Memory | Vendor-ID | LUID       |
|     |                                  |        |            | Device-ID | UUID       |
|---------------------------------------------------------------------------------------|
| 0   | Quadro RTX 8000                  | Yes    | 49398   MB | 10de      | 0          |
|     |                                  |        |            | 1e30      | 772e5a40.. |
|=======================================================================================|
| Processor: Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz | Cores: Unknown | Logical: 12
|---------------------------------------------------------------------------------------|
| Total Memory (MB): 64323 | Free Memory: 29740
| Total Page/Swap (MB): 979 | Free Page/Swap: 979
|---------------------------------------------------------------------------------------|
2021-05-12 07:54:00 [6,740ms] [Warning] [carb.tasking.plugin] Counter 0x7f45b8001f60 released with 2 waiters; spinning until waiters finish
2021-05-12 07:54:00 [6,742ms] [Warning] [carb.tasking.plugin] Counter 0x7f45bc079720 released with 1 waiters; spinning until waiters finish
2021-05-12 07:54:00 [6,810ms] [Warning] [carb.tasking.plugin] Counter 0x7f4598b48230 released with 2 waiters; spinning until waiters finish

Use [Ctrl]-[C] or `kill <pid>` to stop application in the headless mode...

[8.722s] [ext: omni.syntheticdata] startup
[8.730s] [ext: omni.convexdecomposition] startup
[8.735s] [ext: omni.debugdraw] startup
[8.739s] [ext: omni.kit.primitive.mesh-0.1.0] startup
[8.745s] [ext: omni.kit.stage_templates-0.1] startup
[8.757s] [ext: omni.kit.window.content-0.1.0] startup
[8.763s] [ext: omni.kit.window.toolbar-0.1.0] startup
[8.769s] [ext: omni.kit.window.viewport-0.1.0] startup
[8.781s] [ext: omni.isaac.synthetic_utils] startup
2021-05-12 07:54:02 [8,900ms] [Warning] [carb.tasking.plugin] Counter 0x7f45cc007db0 released with 2 waiters; spinning until waiters finish
2021-05-12 07:54:02 [8,908ms] [Warning] [carb.tasking.plugin] Counter 0x7f45bc079c90 released with 1 waiters; spinning until waiters finish
[8.985s] [ext: omni.kit.context_menu-0.1.0] startup
[9.157s] [ext: omni.physx] startup
[9.189s] [ext: omni.isaac.lidar] startup
[9.368s] [ext: omni.isaac.dynamic_control] startup
[9.545s] [ext: omni.isaac.utils] startup
[9.890s] [ext: omni.isaac.robot_engine_bridge] startup
[10.244s] [ext: omni.isaac.dr] startup
2021-05-12 07:54:04 [10,242ms] [Warning] [carb] Acquiring non optional plugin interface which is not listed as dependency: [omni::isaac::dynamic_control::DynamicControl v0.1] (plugin: (null)), by client: omni.isaac.dr.plugin. Add it to CARB_PLUGIN_IMPL_DEPS() macro of a client.
[10.273s] [ext: omni.kit.builtin.init] startup
2021-05-12 07:54:04 [10,259ms] [Warning] [carb.python] connectionhub is obsolete, please update your script to use omni.client
[10.274s] [ext: omni.kit.builtin.material_library] startup
[10.279s] [ext: omni.kit.builtin.profiler] startup
2021-05-12 07:54:04 [10,638ms] [Warning] [carb.tasking.plugin] Counter 0x7f45c80a6b50 released with 2 waiters; spinning until waiters finish
2021-05-12 07:54:04 [10,642ms] [Warning] [carb.tasking.plugin] Counter 0x7f45cc0be120 released with 2 waiters; spinning until waiters finish
2021-05-12 07:54:04 [10,749ms] [Warning] [carb.tasking.plugin] Counter 0x7f4598b48100 released with 3 waiters; spinning until waiters finish
Traceback (most recent call last):
  File "simulate_grasp.py", line 70, in <module>
    main(args)
  File "simulate_grasp.py", line 16, in main
    _mp = _motion_planning.acquire_motion_planning_interface()
RuntimeError: Failed to acquire interface: omni::isaac::motion_planning::MotionPlanning (pluginName: nullptr)
Exiting OmniKitHelper
2021-05-12 07:54:17 [23,831ms] [Warning] [carb.datasource-omniclient.plugin] carb::extras::HandleDatabase<TrueType, HandleType>::~HandleDatabase() [with TrueType = carb::datasource::Subscription; HandleType = long unsigned int]: had 13 outstanding handle(s) at shutdown
2021-05-12 07:54:17 [23,831ms] [Warning] [carb.audio.context] 1 contexts were leaked
terminate called without an active exception
Aborted (core dumped)

```

Do you know where is the problem? Thanks a lot.

**Comment by erasromani** [comment]
@newuhe  Does the following file exist in your isaac-sim _build directory?  

_build/linux-x86_64/release/exts/omni.isaac.motion_planning/omni/isaac/motion_planning/_motion_planning.cpython-36m-x86_64-linux-gnu.so

**Comment by newuhe** [comment]
Thanks for replying. The file exists in my directory.

**Comment by erasromani** [comment]
Can you please include "omni.isaac.motion_planning" under app > extensions > enabledBuiltin within "python_samples/experiences/isaac-sim-python.json" and try again?

**Comment by newuhe** [comment]
It works. Thanks!
